### ISSUE TITLE
Truncated audio for one existing echo-msk feed episode

### ISSUE THREAD

**Issue by usrenmae** [umputun/feed-master#74]
The html web page with Echo Msk episodes references one recent episode which looks incomplete.

Web page: https://feedmaster.umputun.com/feed/echo-msk
Episode name: [Живой Гвоздь: Майкл Кофман / Особое мнение // 07.04.22]
Episode Youtube link: https://www.youtube.com/watch?v=6ibXffJZhJY
Feedmaster's audio link: https://worker01.feed-master.com/yt/media/c5941940daad219ef13119fb61975f4b769333f2.mp3
Feed audio length: 36m20s
Youtube video length: 56m20s

Expected: audio having the length of 56m20s as it's original Youtube video length.

When listening to the audio it breaks just in the middle of the phrase on 36m20s.

**Comment by umputun** [comment]
I can't reproduce the issue and, unfortunately, the box running echo's instance of feedmaster wasn't set up to keep logs outside of the last 5M. I have added a logger, so the next time if smth similar happens, I will be able to check the log.

However, I don't think this was an issue with the feedmaster. This 36m20s file is most likely the actual file yt served at the time we detected it and I believe the file was updated after this. This theory is supported (well, kind of) by 42 minutes difference between publishing time and update time in the original yt feed:

<img width="1164" alt="f2hmknlpl5-20220408-023622" src="https://user-images.githubusercontent.com/535880/162387767-c0ba92f2-0b75-4c9e-9153-aba22ec6570e.png">

I'm pretty certain it wasn't some accident failure/restart of feedmaster, because this RSS entry has duration published, and this happens after the complete file is downloaded.

**Comment by umputun** [comment]
to mitigate such unexpected issues I have added a protected API allowing the removal of meta-data for a particular entry. This way it is possible to manually remove such invalid entries and feed-master will do the rest, i.e. redownload it.

This won't help much In case a podcast client downloaded the episode already. However, in the case of streaming, it should work. I have removed that episode and feed-master redownloaded the full version just fine.

_This is not the ideal solution, but rather a workaround, however, I think this is the best we can do here_
