### ISSUE TITLE
404 error on audio files on non-standard port

### ISSUE THREAD

**Issue by dk76** [umputun/feed-master#75]
In the fm-yt.yml file, I change the example.com address to 192.168.0.2:8097 (and close the brackets on lines 10 and 11) and raise it in the docker.
Everything works, files are created, there is rss. But mp3 files at, for example, http://192.168.0.2:8097/yt/media/445e90abdd57b230424e18b0088b17a029e4a836.mp3 return a 404 error. The file itself is present in the /srv/var/yt directory.
In the logs:
2022/04/08 05:12:40.672 [INFO] GET - /yt/media/445e90abdd57b230424e18b0088b17a029e4a836.mp3 - 192.168.0.2 - 192.168.0.2 - 404 (19) - 14.857µs

Config: [fm.yml](https://gist.github.com/dk76/31b7059dcef72baefc209affdcab6bcc)

**Comment by umputun** [comment]
I have found and fixed an issue caused by the missing yt/media directory which may cause the server (static one, serving mp3 files) to fail on the first run.

I have also updated examples and added a working `fm-yt-local.yml` with the corresponding compose `compose-yt-local.yml`. Tried as a standalone run as well as from the docker and both worked fine and served feeds, files, and UI

**Comment by dk76** [comment]
Now everything is working properly.
